@startuml Reservation
title Reservation
autonumber

actor Patient as Patient
boundary ReservationPage as ReservationPage
participant PrescriptionSmartContract as PrescriptionSmartContract
participant AppointmentSmartContract as AppointmentSmartContract 
control ReservationController as ReservationController
entity Prescription as Prescription
entity Appointment as Appointment
database Database as Database

Patient -> ReservationPage ++ : Get my prescription NFTs
ReservationPage -> PrescriptionSmartContract ++ : Get my prescription NFTs
PrescriptionSmartContract -> ReservationPage -- : Prescription NFTs
ReservationPage -> ReservationController ++ : Retrieve additional data for NFTs IDs
ReservationController -> Prescription ++ : Retrieve additional data for NFTs IDs
Prescription -> Database ++ : Retrieve additional data for NFTs IDs
Database -> Prescription -- : Prescriptions with additional data
Prescription -> ReservationController -- : Prescriptions with additional data
ReservationController -> ReservationPage -- : Prescriptions with additional data
ReservationPage -> Patient -- : Show my prescription NFTs with all data

Patient -> ReservationPage ++ : Click on a prescription NFT
ReservationPage -> ReservationController ++ : Retrieve nearby appointments for the category of the prescription
ReservationController -> Appointment ++ : Retrieve nearby appointments for the category of the prescription
Appointment -> Database ++ : Retrieve nearby appointments for the category of the prescription
Database -> Appointment -- : Appointments nearby for the category of the prescription
Appointment -> ReservationController -- : Appointments nearby for the category of the prescription
ReservationController -> ReservationPage -- : Appointments nearby for the category of the prescription
ReservationPage -> Patient -- : Show nearby appointments for the category of the prescription

Patient -> ReservationPage ++ : Click on an appointment
ReservationPage -> ReservationController ++ : Retrieve appointment ID details
ReservationController -> Appointment ++ : Retrieve appointment ID details
Appointment -> Database ++ : Retrieve appointment ID details
Database -> Appointment -- : Appointment 
Appointment -> ReservationController -- : Appointment
ReservationController -> ReservationPage -- : Appointment
ReservationPage -> Patient -- : Show appointment with all details


Patient -> ReservationPage ++ : Click on "Reserve Appointment"

ReservationPage -> PrescriptionSmartContract ++ : Give prescription NFT to hospital
PrescriptionSmartContract -> AppointmentSmartContract ++ : Give appointment NFT to patient
AppointmentSmartContract -> PrescriptionSmartContract  --: Transfer appointment NFT to patient
PrescriptionSmartContract -> ReservationPage -- : Emit event

ReservationPage -> ReservationController ++ : Reserve the appointment
ReservationController -> Appointment ++ : Reserve appointment
Appointment -> Database ++ : Reserve appointment
Database -> Appointment -- : Appointment reserved
Appointment -> ReservationController -- : Appointment reserved
ReservationController -> ReservationPage -- : Appointment reserved
 
ReservationPage -> Patient -- : Show reservation

@enduml